// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/tenant/schema.prisma",
  migrations: {
    path: "prisma/tenant/migrations",
    seed: "tsx prisma/tenant/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
